### ISSUE TITLE
Basnage 2

### ISSUE THREAD

**Issue by galleron** [WGBS2/Basnage#1]
Just created a file for Basnage 2, using the TEI header of Basnage 1 and some articles encoded by students from P3. Can you look if encoding is satisfactory? If OK, I can add in extra text.

**Comment by WGBS2** [comment]
Will do when I get home. Shopping done. Now a hospital round.

Tomorrow Quimper 

I am on holiday/ retired or something 

G

Envoyé de mon iPhone
